# STORAGE VOLUMES (BIND)
volumes:
  wordpress:
    name: wp_volume
    driver: local
    driver_opts:
      device: ${WP_DATA_PATH}
      o:  bind
      type: none
  mariadb:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: ${DB_DATA_PATH}
      o:  bind
      type: none

# NETWORK
networks:
  inception:
    name: inception


# SERVICES
services:
  nginx:
    container_name: nginx
    build:  ./requirements/nginx/.
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build:  ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build:  ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  # BONUS SERVICES TO BE DEFINED LATER (consider adminer, ftp and redis)

# EOF #
    